spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://mikez-aws-db.cpvuzizi91jj.ap-northeast-1.rds.amazonaws.com:5432/mikezawsdb
    username: awspostgres
    password: SUPERadmin
  servlet:
    multipart:
      max-file-size: 50MB
